/* ============================================================
   AAKASH UDAAN — BLE CONTROLLER
   ------------------------------------------------------------
   !!! DO NOT EDIT THIS FILE !!!

   This block is copied VERBATIM from the original game.js
   (lines 15-85) — the Web Bluetooth code that already works
   with esp32_ble_firmware.ino. Service UUID, characteristic
   UUID, the service-UUID device filter, notification
   subscription, the "roll,pitch" parser, disconnect handling
   and the Recenter zeroing are all unchanged.

   The rest of the game only READS these globals:
     bleConnected, liveRoll, livePitch, rollZero, pitchZero
   and uses targetRoll / targetPitch for smoothing, exactly as
   the original flight model did. The #dot, #statusText,
   #connectBtn and #recenterBtn elements still exist in
   index.html (restyled as arcade cabinet buttons).
   ============================================================ */

/* ------------------------------------------------------------
   BLUETOOTH — must match the UUIDs in esp32_ble_firmware.ino
------------------------------------------------------------ */
const SERVICE_UUID = "4fafc201-1fb5-459e-8fcc-c5c9c331914b";
const CHAR_UUID     = "beb5483e-36e1-4688-b7f5-ea07361b26a8";

let liveRoll = 0, livePitch = 0;      // raw values from the controller
let targetRoll = 0, targetPitch = 0;  // smoothed, used to fly the plane
let bleConnected = false;
let bleDevice, bleChar;
let rollZero = 0, pitchZero = 0;

const dot = document.getElementById('dot');
const statusText = document.getElementById('statusText');
const connectBtn = document.getElementById('connectBtn');
const recenterBtn = document.getElementById('recenterBtn');

async function connectBLE() {
  if (!navigator.bluetooth) {
    alert("Web Bluetooth isn't available in this browser. Use Chrome or Edge on desktop or Android, and open this file directly rather than through another app's preview.");
    return;
  }
  try {
    statusText.textContent = "Requesting device…";
    bleDevice = await navigator.bluetooth.requestDevice({
      filters: [{ services: [SERVICE_UUID] }]
    });
    bleDevice.addEventListener('gattserverdisconnected', onDisconnected);
    statusText.textContent = "Connecting…";
    const server = await bleDevice.gatt.connect();
    const service = await server.getPrimaryService(SERVICE_UUID);
    bleChar = await service.getCharacteristic(CHAR_UUID);
    await bleChar.startNotifications();
    bleChar.addEventListener('characteristicvaluechanged', onTiltData);

    bleConnected = true;
    dot.classList.add('connected');
    statusText.textContent = "Connected: " + (bleDevice.name || "ESP32");
    connectBtn.textContent = "Disconnect";
    recenterBtn.disabled = false;
  } catch (err) {
    console.error(err);
    statusText.textContent = "Connection failed";
    setTimeout(() => { if (!bleConnected) statusText.textContent = "Not connected"; }, 2500);
  }
}

function onDisconnected() {
  bleConnected = false;
  dot.classList.remove('connected');
  statusText.textContent = "Disconnected";
  connectBtn.textContent = "Connect ESP32";
  recenterBtn.disabled = true;
}

function onTiltData(event) {
  const text = new TextDecoder().decode(event.target.value);
  const parts = text.split(',');
  if (parts.length === 2) {
    liveRoll = parseFloat(parts[0]);
    livePitch = parseFloat(parts[1]);
  }
}

connectBtn.addEventListener('click', () => {
  if (bleConnected && bleDevice) bleDevice.gatt.disconnect();
  else connectBLE();
});
recenterBtn.addEventListener('click', () => {
  rollZero = liveRoll; pitchZero = livePitch;
});
